### ISSUE TITLE
change title on excel export

### ISSUE THREAD

**Issue by tineml** [IFRCGo/cbs#1107]
feedback from Mozambique: 

The file names of the excel export are not very friendly to automatic sorting on my computer. It would be better if it had: YYMMDD in front of it. e.g. "190502-case-reports-2019-May-02.xlsx"

**Comment by tineml** [comment]
![caserep](https://user-images.githubusercontent.com/22004770/58766380-3ac6ee80-857e-11e9-8a7b-8187833d86f2.png)

**Comment by esp0** [comment]
Please expand on why the current format (CaseReports-YYYY-MM-DD.xls) are not friendly to automatic sorting. I think it looks good as it is.

**Comment by tineml** [comment]
I think this is due to the export not ending up in cronologic order when year is not first. @raubreywhite, can you elaborate?

**Comment by raubreywhite** [comment]
I think there is some confusion due to there being a delay and information not making it everywhere :-)

When I said this on slack, the file name was "case-reports-2019-May-02.xlsx"

@esp0 then changed it to "CaseReports-YYYY-MM-DD.xlsx"

@tineml then looked at my comments and opened this issue, not knowing that @esp0 had already fixed it.

(At least, I think this is what happened).

**Comment by tineml** [comment]
That sounds like the right conclusion. Thank you @esp0 for being so quick at fixing things and sorry for being late in following up! Trying to gather stuff from here and there. Then I close this issue.
