### ISSUE TITLE
Create "anonymous" case report for unknown phone numbers

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#170]
If a text message is received from a phone number that **does not** exists in our data collector store, we need to create an "anonymous" case report and persist it. When the case report has been created, an "AnonymousCaseReportCreated" event must be emitted.  

**Further information**
We know that a text message has been received by listening to and [processing](https://github.com/IFRCGo/cbs/blob/master/Source/VolunteerReporting/Read/TextMessageRecievedFeatures/TextMessageReceivedEventProcessor.cs) the "TextMessageReceived" event.

Path to solution: https://github.com/IFRCGo/cbs/tree/master/Source/VolunteerReporting

**Comment by Velcrow81** [comment]
After feedback from @einari , AnonymousCaseReportRecieved will be emitted instad of CaseReportRecieved if DataCollector is unknown. That means that DataCollectorId will no longer be nullable on CaseReportRecieved

**Comment by karolikl** [comment]
Is the case report stored in the db after it has been processed?

**Comment by Velcrow81** [comment]
Nope. Just the event. But I can make it happening 😊

16. okt. 2017 21:40 skrev "Karoline Klever" <notifications@github.com>:

Is the case report stored in the db after it has been processed?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/IFRCGo/cbs/issues/170#issuecomment-337011957>, or mute
the thread

**Comment by karolikl** [comment]
I created a new issue for storing the case reports: #234
