### ISSUE TITLE
Setup new project

### ISSUE THREAD

**Issue by EvyTurk** [IFRCGo/cbs#171]
### Description
X country is starting the project and giving permission to initiate the project. 
The necessary requirements form the user setting up new project are described in #35, #37, #54 and #62.

**Comment by roarfred** [comment]
Is the combined set of issues (#35, #37, #54 and #62) a part of the MVP milestone, or should we try to describe something more specific?

(It is a bit unclear to me if the MVP is to have an event for the creation of a new project, if it is to have a working UI in the admin project to fire such an event, or if it is to have the complete project setup feature implemented)

**Comment by karolikl** [comment]
I believe the issues referenced here are way too high-level and need to be broken down into more fine-grained issues. 

The MVP will not include all the features in the referenced issues, especially since alerts (#54) is out of scope for the MVP. We need to agree on the scope with the Red Cross, but I would prefer if the scope of the MVP includes the creation of a project (from a working UI) with limited properties (maybe name + location is sufficient and the rest can be added later on?). The MVP could for example allow any health risk to be reported and the selection of health risks on a project can be added later.

**Comment by alexanderhoset** [comment]
Needs to be combined with #35, #37, #54 #62 and documented

**Comment by alexanderhoset** [comment]
Moved to https://trello.com/c/DIzoOZ9Y
