### ISSUE TITLE
When a new data collector is created, check for anonymous case reports linked to the data collectors phone number

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#184]
When a new data collector is created, he/she might already have sent in reports from an unknown phone number. These have then been saved as "anonymous" case reports. 
So after the data collector has been created, we need to check for anonymous case reports linked to the data collectors phone number. If any anonymous case reports are found, the data collector ID should be added to the report and the CaseReportIdentified (#207) event should be emitted. 

**Further information**
We know that a new data collector has been added by listening to and [processing](https://github.com/IFRCGo/cbs/blob/master/Source/VolunteerReporting/Read/DataCollectorFeatures/DataCollectorEventProcessor.cs) the "DataCollectorAdded" event (#139). 

Path to solution: [https://github.com/IFRCGo/cbs/tree/master/Source/VolunteerReporting](https://github.com/IFRCGo/cbs/tree/master/Source/VolunteerReporting)

**Comment by roarfred** [comment]
I think the correct event to listen for is PhoneNumberAdded. This will be received independently from the DataCollectorAdded event (which doesn't really have a phone number)

**Comment by karolikl** [comment]
Your are absolutely right. Thanks! Update:

**Further information**
We know that a new phone number has been added to a new or existing data collector by listening to and processing the "PhoneNumberAdded" event (#139).

**Comment by Velcrow81** [comment]
Working with events is new to a lot of us and it takes some getting used to. If I process the PhoneNumberAdded event (in Read project?) and find an  "anonymous" case reports that should result in a CaseReportIdentified event beeing emited. However, that means that if we replay the events, another CaseReportIdentified will be emited witch will change the state of the system. My solution would be do change the Process to ProcessOnce once the system supports that (Einar is going to add it), so that this check is only done once per phone number ( never used the word once that many times in a sentance before:)). Is there a better way to do this? Or is that the solution for "every" scenario where we process an event that emits another event?

**Comment by roarfred** [comment]
I don't think that simply emitting an event inside an event processor is a reason to use ProcessOnce. Rather, we should try to keep our event processors idempotent, but only if we can not, we should use the ProcessOnce version. Now guessing, but you might want to both store some data and send an sms from the same event. I guess we should have both a Process (to save data) and a ProcessOnce (to send sms) for the same event. As I understand, you can have multiple event processors, but you can't rely on the order they are called being deterministic.

A good reason for firing events over again is that we might be using these to rebuild or own read models. However, there might be other parties listening in on us, and if I got this right, we should be able to rely on the underlying infrastructure to not cause duplicates. Einar explained to me some ID of an event to be injected into the Emit-call, which yet wasn't implemented, but I think it was meant to prevent just this.

**Comment by karolikl** [comment]
I recommend reading the docs on Idempotency of events: https://github.com/IFRCGo/cbs/blob/master/Documentation/Architecture/events.md#idempotency

It states that we can assume that events are delivered once and only once, 
_"The underlying system guarantees ordering of events when replaying and also that your event processor can assume that events are being delivered once and once only. This is built into the underlying system being used. You as a developer do not have to worry about this."_

**Comment by Velcrow81** [comment]
Thanks for your feedback :) 

I agree that updates of any read models should happen every time a specific event occurs (in this case PhoneNumberAdded) and when it is replayed. This can be solved by a specific processor for the read model. This is idempotent and will be the same everytime it is replayed giving the same result. A good example is that processing the PhoneNumberAdded event whould add a phone number to a datacollector. 

However, for the domain logic of identifying anonymous case reports I am unable to see the same. When a phonenumber is added to a datacollector, an external system emits an event. This event is captured in our system, which process it in at least two processors (read models and domain). The domain logic checks if there are any anonymous case reports with this phone number and emits new events for each case report identified. Emited events are stored in our event store, processed by any read models and communicated to other systems. 

Replaying these events by processing everything again would yield the following: 
1. PhoneNumberAdded -> CaseReportIdentified (new event)
2. CaseReportIdentified (the same emited the first time)

If we replay the events but process PhoneNumberAdded only once in the domain logic:
1. PhoneNumberAdded
2. CaseReportIdentified (the same emited the first time)

My understanding of _"The underlying system guarantees ordering of events when replaying and also that your event processor can assume that events are being delivered once and once only"_ is that a specific PhoneNumberAdded event is given to each event processor once. That is OK for the read model processor, but not for a processor that emits another event, since the resulting event is already stored and is also garantued delivered once to any processors that need it. 

It would be great if the event system solves this magically without requiring ProcessOnce, but I am unable to understand how and can only see ProcessOnce as the solution in this case. I am very aware of event souring beeing my new and shiny tool which I must use to solve any and all problems :)  Help me see alternatives. 
Help us @einari, you are our only hope :)

**Comment by einari** [comment]
Hehe... Lol..  I'll come dressed with cinnabons. 
I'm almost done bringing in doLittle to this and this had caused quite a few refactorings. Amongst others to this particular scenario. I'll probably have a PR tomorrow. 

Teaser ; AggegateRoot will be there, which is a type of EventSource. Other giveaway - SMS infrastructure skeleton, with a test controller. It is hooked up without having the TextMessageReceived events - as they are not domain events.

**Comment by einari** [comment]
Do we have an issue for your example scenario? I think I'd like to play with it a bit to see what the answer is; sometimes easier to just try things out. 

I think the answer will be a domain Policy - but not entirely sure.

**Comment by Velcrow81** [comment]
It's this issue and go for it. When the external event PhoneNumberAdded comes into Volunteer Reporting, we will process it. A consequence of this processing might be that a new CaseReportIdentified event can be emited. Or am I not getting your question?

**Comment by Velcrow81** [comment]
Any progress on this @einari?

**Comment by einari** [comment]
Sorry - there has not been any time for me since we last talked about this. I've been discussing it in more detail with @smithmx. There is an opportunity for us to treat replay very differently and if it is a policy that is directly involved in producing the event, we could by that fact just ignore the producing of the second event. That would mean that the system would just magically ignore the production of the second event during replay. We could either lock it down and say this is the rule for any events being produced during replay, or we could say that if being produced from a Policy - this is what should be done. Or thirdly we could be very strict and say events with same SHA would be ignored if for instance the last produced event for that type matches that SHA. 

I just want to sanity check these statements before we write in stone that thats the approach.

**Comment by einari** [comment]
We had a bit of an epiphany a couple of days ago, which we think will make this a lot simpler. 
Right now the building block we have for dealing with events is an event processor. This is a very generic "catch all" thing and leads us down the path of confusion. 

We want to introduce more specific ones for specific purposes, that makes it a lot easier to have control things during replay as we then have the necessary metadata to deal with the different types of event processors differently. 

So, for guaranteeing for actions that you don't want to happen more than once - we will introduce a building block that can be implemented for that purpose. 

Replaying with the building block we have now is a bit hard - basically because the runtime have no idea what your processor is doing inside it. In doLittle we want to move away from the approach of implementing the event processors like it is now. Instead start identifying what you want to do and allow you to declaratively tell it what to do. One of the things we've been working on for a while is a Map/Reduce engine that will be able to deal with the typical projections one does from events, rather than dealing with them imperatively - see more details [here](https://github.com/doLittle-Entropy/MapReduce). Moving away from the `ICanProcessEvents`thing to something like this would we thing we'd crack replaying and a lot of other issues.

**Comment by Velcrow81** [comment]
Copy that. Carrying on as before :)

**Comment by Velcrow81** [comment]
@einari : New things that confuse me :)

Where should we process the PhoneNumberAdded event and generate CaseReportIdentified? Should that be in the domain project? Add a eventprocessor that process PhoneNumberAdded which calls the CaseReport aggregate root leading to CaseReportIdentified being applied? 

And how should the rest of the system respond to CaseReportIdentified? If we identify a CaseReportFromUnknownDataCollector, should we then delete this entity and create a new CaseReport in the ReadModel? And should we then emit a new CaseReportReceived since we now know the DataCollector? This would allow other systems to only listen for CaseReportReceived and they would get that when a case is received or after data collector is identified or when content is fixed and datacollector is identified. Or would all other systems have to update their read models in the same way as VolunteerReporting do? My gut is telling me that this is the correct event flow:

CaseReportFromUnknownDataCollectorReceived
PhoneNumberAdded
CaseReportIdentified
CaseReportReceived (new Id or same as CaseReportFromUnknownDataCollectorReceived?)

That way i.e. Alerts could be built just listening for CaseReportReceived since VolunteerReporting will emit this event eventually after a case report have been identified. What is your take on this Einar?

**Comment by einari** [comment]
Good gut :) 

This is what is typically a policy - something that responds to an event and can leverage the domain to get its work done, for instance an Event Source / Aggregate - and it would apply new events. 
I suggest you add a Policy project, it would take a dependency to the Events and Domain projects. Since this is a missing building block right now, you just mark it as an `ICanProcessEvents`and it could take an `IAggregateRootRepository<>`as a dependency and work with the aggregate.

As for the ReadModel side of things, I think as you describe; delete old and create a new and different document makes perfect sense.

The `CaseReportReceived`event could be applied, but through the appropriate aggregate - governed by the Policy.

**Comment by Velcrow81** [comment]
I'll have yet another go at this then. Thank you for your reply :)

**Comment by Velcrow81** [comment]
@einari : How are we supposed to use IAggregateRootRepository<CaseReporting> in the Policy to find unknown case reports? I have added a Policy project and a class that brags about ICanProcessEvents with a Process(PhoneNumberAdded @event) method. The IAggregateRootRepository<CaseReporting> instance have a Get method that takes an EventSourceId (which means CaseReportId for this Aggregate) and that is the only query I can see. The CaseReportFromUnknownDataCollectorReceived event results in a CaseReportId for that case report, but that is not known in the policy when I process PhoneNumberAdded. How can I find aggregates with unknown data collectors? Do I need to add methods that replay events with given query parameters like phone number and return the EventSourceId? And then apply events to that aggregate?

**Comment by einari** [comment]
Let me see if I can elaborate a little bit - with the chance of completely misunderstanding it all.. :) 

Anywho.. Dealing with unique identifiers is different, you need to be able to know the ID either by a natural key representing it, or be able to uniquely generate it when needed. 

A natural key is something that is considered unique in the domain - examples of this could be for instance the Social Security Number. It could be considered a unique identifier of a person and a natural key that can be provided. This natural key is not being used directly internally. Everything internally are Guids. That means you need a map to map from this to a Guid if you want to work with a natural key. 

Internally I mention that everything is a Guid - with a good reason. It is something that can be uniquely created at any point in time and we don't have to rely on a classic data store to be generating it for us and return it to the user. In a distributed system we can't be waiting for something to generate it - a Guid is then brilliant, as we can even generate these in the frontend. A frontend would then have the knowledge of what it sent off to the backend as a command with the Id on it. If it wanted to call upon a query to get read models back, it would already have the Id and could do that. The optimal solution would at that point be that the client got notified with relation to what it just did according to the correlation id of the command it sent in. But thats a different story all together. 

That was a bit of technical context for the answer I will try to give for your scenario. :) 
The aggregate here is not about the case reporter - it is a way to model the reporting of case, it is in fact the case reporting you're modelling - not modelling a DataCollector aggregate that reports a case. Since the data collector is unknown, you don't really need to identify it - it is in fact going to be on the read side of things an object representing unassigned cases. For the policy that will deal with the hook up when a data collector is added to the system, it needs to have access to the read models for unassigned cases. It would then try to match them by its secondary key; phone number and issue an event that signals the match and you'd have a processor that converts it from Unknown to a Known read model. The policy is allowed to do all of this - it is a coordinator and needs to know about the different parts.

Hope that made sense?? 
I'm sorry for the lengthy answer, it is hard to explain without giving some background and motivation for some of the design decisions.

**Comment by Velcrow81** [comment]
Thanks for the lengthy answer :) I thought that I could not rely on the read model, but that makes things a lot easier. On Dec 4th, you said: "I suggest you add a Policy project, it would take a dependency to the Events and Domain projects" and since you did not mention the Read project, I thought that I had to get it to work with just the domain. I thought that this had to do with the read models being eventually consistent, but I guess that was yet another misunderstanding on my part. I will give this another go!

**Comment by einari** [comment]
Lets give that a try for now and see how it looks. It might be completely off for what we know. For this particular scenario the eventual consistency wouldn't be a problem. But I can see that it could be for other scenarios and this might not be 100% ideal solution. So don't necessarily get 100% wedded to it all - you know; learning by failing and all..  :)

**Comment by einari** [comment]
A way to give some flexibility in how you actually do this, without taking a dependency directly to the read side would be to define a delegate that we could hook with the IoC container to work with read models right now. 

So for instance: 

```csharp
public delegate DataCollector GetDataCollectorFor(MobileNumber mobileNumber)
```

Then you could take a dependency to this and have it hooked up in a module that was for this and it basically just implemented it by going to a read model repository and get it.
