### ISSUE TITLE
Ensure cake script runs xunit tests

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#242]
In /Build/build.cake, there is a Task running unit tests which outputs a "todo" message:

`Task("Run-Backend-Tests")
    .IsDependentOn("Build-Backend")
    .Does(() =>
{
    Information("Not quite sure which unit testing framework we're using yet?");
});`

We have now selected xUnit as the preferred unit testing framework, so this Task should execute the unit tests.

**Comment by roarfred** [comment]
Would be great to get this one completed, I have three PRs enqueued, failing because of xunit tests :)

Started looking at running the tests from cake, and found it fairly simple to add into the build.cake file, given that I get the path to the build folder right. However, there is no mention of cake in the AppVeyor log, so I assume this task takes a bit more effort, both to disable the default build in AppVeyor and to enable the cake thing. If I can be of any help, please let me know...

**Comment by karolikl** [comment]
I can fix this today. 

Brief explanation of why appveyor doesn't reference the cake script: Appveyor calls the build.ps script which kicks off build.cake.

**Comment by roarfred** [comment]
I got the cake build running locally with xunit tests... Was the problem more related to Appveyor failing when executing xunit tests?

**Comment by karolikl** [comment]
Yes, I don't think AppVeyor was able to run the xunit tools I specified. The blog post Anders shared above looks like a brilliant way to do it, so I'll try that.
