### ISSUE TITLE
InvalidReportFromUnknownDataCollectorReceived

### ISSUE THREAD

**Issue by Velcrow81** [IFRCGo/cbs#245]
public Guid CaseReportId { get; set; }
        public string Origin { get; set; }
        public string Message { get; set; }
        public IEnumerable<string> ErrorMessages { get; set; }
        public DateTimeOffset Timestamp { get; set; }

**Comment by einari** [comment]
In the PR #272 - I took the liberty to change some of the naming. I might be completely off, so please correct me. But I moved away from Anonymous to UnknownDataCollector. 
So if you were to go with the things I've already put in, I called this:
`InvalidReportFromUnknownDataCollectorReceived`

The reasoning behind is that from a domain perspective we're trying to capture what happened in the system - rather than the technicality of a text message parsing failure. 

One thing we also would need to discuss for these types of events is wether or not the `PhoneNumber` is the property we're looking for. I put in `Origin`- but that is not really saying much either. 

This might also be OK to have as PhoneNumber - and maybe we should reflect its "origin" in the naming. 

If it is coming from somewhere else, you'd validate the command going in. With a text message you basically can't validate it and reject in the same way.

**Comment by Velcrow81** [comment]
Changed the name. When it comes to PhoneNumber (or OriginPhoneNumber if that is even better), this is the only identifier we have to enable future identification of the data collector. I can think of no other scenarios where the data collector will be unknown. If its through an app or web site, the datacollector will have to log in before sending reports. Text messages is the only input that I can think of that comes from unknown senders and then the only identifier is the phone number. Thoughts?

**Comment by Velcrow81** [comment]
Updated because of discussion in #133

**Comment by eprom** [comment]
Closing. Summarised events are found here: https://github.com/IFRCGo/cbs/wiki/Events, Detail information about each event will be documented.
