### ISSUE TITLE
Move CaseReportReceptionFeatures from Web

### ISSUE THREAD

**Issue by roarfred** [IFRCGo/cbs#252]
There's some duplication and it just doesn't seem right to have the TextMessageContentParser and the TextMessageRecievedEventProcessor (mind the spelling) in the web project. These should be moved to the read project.

**Comment by Velcrow81** [comment]
I can agree that it should not be in the web project. It was put there temporarily becuase of its close link to the sms gateway. Im am still not sure how they will interact (we might remove the TextMessageRecieved event and replace it with something in the sms gateway instead), but that will become cleat after @einari adds some missing infrastructure. 

Moving it is ok, but I think it should be in the domain project instead of the read project, since this code generates domain events and is part of the Volunteer Reports domain logic. What are your thoughts on this @roarfred ?

**Comment by roarfred** [comment]
I am afraid I already snack these out as part of another PR, about writing a test to ensure a zero text message still created a case report event (#154). As these events rely on the read model, I assumed this was the right place, as I see there is no reference from the Events project to the Read project, but vice versa. Please let me know if you disagree, I am still learning this stuff, and might wrong again :)

**Comment by Velcrow81** [comment]
I am also learning this (and failing a lot) and my understanding of the the read models is that they should just process events and update the read model based on events. It should never change the state of the system by emiting events. And since the moved code emits a boatload of events, I believe that it should be placed in the Domain project (witch should have a reference to the Event project and the Read project)

**Comment by roarfred** [comment]
I was trying to re-read a little about this on dolittle.io. What is reasonable clear is that there's something defines as an [Event Source](http://www.dolittle.io/Backend/Events/event_sourcing.html), and its usually an [Aggregate Root](http://www.dolittle.io/Backend/aggregate_root.html). It's stated in this documentation that the Aggregate Root is purely about the WRITE process.

Also, looking at the eShopOnContainers demo project, you'll see the [aggregate roots](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Services/Ordering/Ordering.Domain/AggregatesModel) defined in a domain project, and they are accessed from the command handlers in the API project. The underlying command is here defined in the Web API project, not in the domain project, so this is not quite as clear. (In our example project, the commands are defined in the domain project)

Again, I think I am starting to get a grasp of this, and I think you are right about having aggregate roots in the domain project, let these be instantiated from a command handlers in the same project, and let them be the source of any event in the system. Having a rather low right-to-wrong rating the last weeks, I think we should again ask the guru for help... @einari, would you please enlighten us again?

**Comment by Velcrow81** [comment]
Hehe. This is also how I understand it and that is why this case has been difficult. I defined it in the web project for now since the TextMessageRecieved kinda was a command issued from people sending text messages. The TextMessageRecieved event was introduced at the codeathon as a temporary solution since the SMS gateway was not ready, but it will be soon. I am not sure how it will be implemented, but it might end up sending commands to the domain project and the moved code will be rewritten as an aggregate root there. Time will tell. Or @einari :)

**Comment by einari** [comment]
Yup. I've refactored quite a bit. Removed the TextMessageReceived event in favor of hooking up to new infrastructure skeleton I've created. Introduced a CaseReporting aggregate root that will produce the domain events. Also moved this around a little bit. 

Great discussion Btw! You'll probably see some differences in how doLittle does things and the eShopOnContainers project. 

Been traveling most of today and been writing code whebbpossible. Still a couple of minor things left. So unfortunately not able to do the PR today with all the changes. But tomorrow it'll come.
