### ISSUE TITLE
Persist invalid case reports 

### ISSUE THREAD

**Issue by alexanderhoset** [IFRCGo/cbs#298]
### Description

#234 does it for valid reports, but we need to list the errors also 

As we are emitting a InvalidCaseReportRecieved(can not find it under event project) event and an InvalidAnonymousCaseReportRecieved(#215 under a different name, rename #215?) event, we could create two event processors where we capture our own events and store the contents of the case reports in MongoDB, read model and expose an API(extend #235?) 

Anonymous and known invalid case reports should be stored separately.

**Comment by roarfred** [comment]
I think the conclusion was to use the term Unknown Data Collector over Anonymous, as it more accurate describes that the report can be identified, just we don't know who sent it

**Comment by alexanderhoset** [comment]
Ahh ok, that explains it 👍

**Comment by roarfred** [comment]
Btw, I found some irregularities... 
1. A CaseReportReceivedFromUnknown... has a PhoneNumber, whereas the Invalid-version og the same has an Origin property. How do we know which one is right?
2. Also, neither the CaseReportReceived nor the InvalidReportReceived has a timestamp. I figure this will be useful information for the end user, was it just left out by accident?

**Comment by karolikl** [comment]
1. I believe Einar renamed from PhoneNumber to Origin to support other forms of receiving case reports (in the future, SMS will not be the only way). But for our text message reports, Origin will contain the phone number of the sender. 

2. They should all have a timestamp, I believe this has simply been left out by accident.

**Comment by roarfred** [comment]
Seems like @einari did a trick with the timestamp, where he used a ISystemClock from doLittle, to tag the items from the read model. I think this was just a shortcut to get some useful data in the system, unless the ISystemClock is doing some magic to always be in sync with events, also during playback

**Comment by einari** [comment]
1. The PhoneNumber -> Origin thing might not be the correct name or approach - but the reason was as you said to support multiple origins. Question is if it should be different events instead, as the other origin would not have a specific origin, meaning it would be from something like an app or a web interface. Then you don't really want to store the IP address its coming from or something like that, so the origin kinda only have meaning when it is coming from a telephone number.
2. Timestamp - that's a mistake by me; I over-optimized - thinking it already gets time stamped in the metadata when the event is stored and published. This metadata is however not accessible by the `EventProcessor` yet. As for the `ISystemClock` - it is not doing anything special, its just an abstraction for time. Makes it a lot easier to do testing having this abstraction in place, if everything uses `DateTimeOffset.UtcNow`your tests might become very brittle or hard to write at all.

**Comment by roarfred** [comment]
I think this one is complete. I just verified all these events do have a timestamp and the ones from unknow data collectors have a consistent use of origin. Same goes for the read model.
