### ISSUE TITLE
Connecting text messages to a project

### ISSUE THREAD

**Issue by roarfred** [IFRCGo/cbs#307]
In a discussion with @alexanderhoset, we saw the need for having the case reports associated with a project. Pretty obvious, but we couldn't really know for sure where and how an incoming SMS is recognized to be within a specific project. This might also depend on the type of SMS Gateway we are planning on, and  if a gateway will ever serve multiple projects.

We could use both location information, senders phone number or -prefix (nationality or matching data collector), but there might be shortcomings and differences.

While at it, I also wonder how I can determine the preferred language for replying to an unknown number. Might be related to this, but we'll move it to a separate issue if not.

**Comment by karolikl** [comment]
If the same gateway is used for multiple projects, I assume the SMS keyword or the number used will be project specific so that we can route the messages to the correct project. Maybe @ravndal has more input into this?

I find using location data risky as we then assume there will never be several projects within the same area, and this limitation can cause trouble in the future. 

As for the preferred language, could the project have a default language to be used?

**Comment by ravndal** [comment]
Working on a Gateway infrastructure application that will handle all the mapping between incoming messages and projects. 
* Normally we will use keywords as map to one or more projects. 
* In cases where we do not have a keyword, we can map a specific gateway to a project. 

The application will allow multiple keywords and multiple gateways to map to one or more projects.
