### ISSUE TITLE
Upgrade handlebars.js in Admin project

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#315]
### Description
handlebars.js version 1.3.0 has a known security vulnerability. Upgrade to newest version.

**Comment by fredrik-lundin** [comment]
This one is a bit trickier than just updating a package. handlebars.js is a deeply nested dependency of the angular cli package. This means we don't have it included directly in our package.json file, where we can change it. Changing the version in the lock file directly might affect the behavior of the CLI (since the the CLI version we are using is using some packages that depend on this version of handlebars.js). 

Could be that updating the CLI to start with is a better approach. And if the dependency is not updated in the new version of the CLI, then we might look into forcing a newer version via the lock file.

**Comment by roarfred** [comment]
Seems like the angular-cli project adressed this issue just a few days ago:
https://github.com/angular/angular-cli/issues/8534

Anyone see a reason not to upgrade?

**Comment by alexanderhoset** [comment]
@fredrik-lundin  I was just about to say the same, 
Can always try in the example project first

**Comment by fredrik-lundin** [comment]
@roarfred @alexanderhoset  it looks like their (angular cli team) fix is merged to master, but not yet included in any release. So I think we have to wait until they release it before we upgrade

**Comment by roarfred** [comment]
@fredrik-lundin, sounds like a reasonable risk assessment to me :)

**Comment by karolikl** [comment]
Sound good!

**Comment by anderaus** [comment]
Released last night: https://github.com/angular/angular-cli/releases/tag/v1.5.3
