### ISSUE TITLE
Case reports should exist in the context of a project

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#369]
Today, all case reports are stored and displayed together, regardless of which project they belong to. 

We need to make case reports project specific. We can assume that the following events will contain a projectId (the SMS gateway, which is outside the VolunteerReporting project, should be able to look up which project a report belongs to): 

- CaseReportReceived
- CaseReportFromUnknownDataCollectorReceived
- InvalidReportFromUnknownDataCollectorReceived
- InvalidReportReceived

All APIs retrieving casereports will need to pass in a projectId, to receive the reports for a certain project.

**Comment by karolikl** [comment]
Ref #307

**Comment by Velcrow81** [comment]
After discussions on last codeathon, it was agreed that case reports should not know of projects in Volenteer reporting. If it is needed, it should be shown in a read model in Reporting context, or possibly in the admin page as part of project managment. It should be a projects responsibility to know which data collector it "owns" and because of that which case reports it "owns". 

Suggest that this issue be closed

**Comment by karolikl** [comment]
Agreed! Closing :)
