### ISSUE TITLE
Validation of the different user types is faulty

### ISSUE THREAD

**Issue by kamperud** [IFRCGo/cbs#452]
When adding a user through the api there are several validation rules in 
AddStaffUserValidator that are not working as intended.

Needed:
- Create unit tests
- Fix validation rules

For example:
When role is empty from the frontend, it is defaultet to the first Enum value in Role, and therefore the validator checking for notEmpty() is never going to trigger an error. Suggestion to make a Role.None as the default, and validate based on that being an illegal value. We had trouble making this work as well, so it needs some love.

**Comment by smithmx** [comment]
I'm now backing away from the Role.None approach.  We are actually creating an invalid value on our enum to support parsing of requests / hydrating of objects.  This feels wrong.

Although I'm not a fan of them in general, maybe we should make the enum nullable.  In this case, the missing enum will be null and can be caught with a NotNull() or NotEmpty() check.  This would also help us with the second issue which is why the rules weren't firing properly.  If we have a null we can check the cascading rules see if the NotNull rule works and then the IsInEnum() value.  If this doesn't work as expected, I suggest we use a Must() rule and do Enum.IsDefined to see if it is a valid value.

**Comment by woksin** [comment]
@smithmx Isn't this solved?
