### ISSUE TITLE
404 not found when refreshing http://dev.cbsrc.org/reporting/case-report/list

### ISSUE THREAD

**Issue by woksin** [IFRCGo/cbs#554]
When I refresh the page when I'm on http://dev.cbsrc.org/reporting/case-report/list I get a 404 Page not found nginx/1.13.9

**Comment by karolikl** [comment]
From the nginx ingress controller logs: 

10.244.0.1 - [10.244.0.1] - - [09/Apr/2018:15:34:14 +0000] "GET /reporting/case-report/list HTTP/1.1" 404 209 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299" 475 0.001 [default-cbs-volunteerreporting-frontend-service-80] 10.244.0.173:80 572 0.001 404

**Comment by jakhog** [comment]
I think that this is because the frontend nginx-servers only serves the static index.html file if you navigate directly to "/" or "/index.html", so when you try to load something else - like "/case-report/list" - it responds (correctly) that there is no such file.

I'm looking into this, shouldn't be a very hard thing to fix
