### ISSUE TITLE
Incorrect parsing of SMS: 7#A#1#2

### ISSUE THREAD

**Issue by karolikl** [IFRCGo/cbs#657]
In the field test, an SMS was received with the following content: 7#A#1#2

This was parsed in the following way: 
{"id":"4bfdf496-0e13-421f-9881-8c81092caf4c","status":0,"dataCollectorId":{"value":"22eda152-9080-4ada-ae14-39b3ca914b84"},"dataCollectorDisplayName":"izabella","healthRiskId":{"value":"51b92f4d-f14f-4ce9-9134-d766db5c3f80"},"healthRisk":"Cholera ","message":null,"numberOfFemalesAgedOver4":0,"numberOfFemalesAges0To4":0,"numberOfMalesAgedOver4":1,"numberOfMalesAges0To4":0,"timestamp":"2018-04-13T08:53:02+02:00","location":{"latitude":2.0,"longitude":2.0},"origin":"+4746877364","parsingErrorMessage":null}

This message should have resulted in an error as it is not a valid format.

**Comment by woksin** [comment]
This indicates that we have to take a closer look at the Text message parsing it seems

**Comment by jakhog** [comment]
Seems to come from here
https://github.com/IFRCGo/cbs/blob/7eda79b2f02b1e443c690059082d5e37a8b6ed28/Source/VolunteerReporting/TextMessaging/TextMessageParsingResult.cs#L18
and here
https://github.com/IFRCGo/cbs/blob/7eda79b2f02b1e443c690059082d5e37a8b6ed28/Source/VolunteerReporting/TextMessaging/TextMessageParsingResult.cs#L34-L38

So in this case, the `A` is completely disregarded, and the message still passes as correct since it has three numbers.

It should just be a matter of changing the `ValidateAllFragmentsHasValue()` to something like `ValidateAllFragmentsIsNumber()` and checking the `fragment.IsNumber` in the loop
