### ISSUE TITLE
Weekly epicurves by age/sex frontend

### ISSUE THREAD

**Issue by raubreywhite** [IFRCGo/cbs#856]
Please see the [overall documentation for analytics](https://github.com/IFRCGo/cbs/blob/master/Documentation/Projects/Analytics/index.md) for more information.

This is the frontend for https://github.com/IFRCGo/cbs/issues/857

![unnamed-chunk-6-1](https://user-images.githubusercontent.com/1532091/48144925-0920ca00-e2b2-11e8-86c3-d8a4645ae08e.png)

Here we display four weekly epicurves, one for each age/sex combination.

Important to note:

-   We display `year-isoweek` on the x-axis
-   Weeks with zero cases must be displayed
-   Y-axis remains the same height for all panels, to allow for easy
    comparison

**Comment by raubreywhite** [comment]
Fake json data: `cbs/Documentation/Projects/Analytics/fakejson/epicurve-by-week.json`

This is an extension of the graph Epicurve by week" (frontend issue: https://github.com/IFRCGo/cbs/issues/845, backend issue: https://github.com/IFRCGo/cbs/issues/846).

**Comment by raubreywhite** [comment]
Please note that in principle, this will be superseded by: https://github.com/IFRCGo/cbs/issues/922

**Comment by karolikl** [comment]
A static version of this chart has been generated in the Web Template using Highcharts, see `Documentation/Projects/Analytics/Web%20Mockup/Weeklyepicurvesbyagesex.html`, however this is dodged by sex & age instead of using a facet grid with sex & age as shown in the diagram above. 

**Remaining work:**
- Generate a static version of this chart that **uses a facet grid** in the Web Template using Highcharts: `Documentation/Projects/Analytics/Web%20Mockup/Weeklyepicurvesbyagesex.html`. The existing chart that is dodged instead of using a facet grid can be kept as well.
- Add Highchart to the React frontend
- Generate chart based on user input, as mentioned by Richard above (#922)
- Query backend for data

**Comment by raubreywhite** [comment]
No longer relevant with new UI plan.
