### ISSUE TITLE
Registered data collectors being listed as "unknown"

### ISSUE THREAD

**Issue by RebeccaBushby** [IFRCGo/cbs#885]
**Describe the bug**
Sometimes, the platform doesn't recognise numbers which are registered (i.e. linked to a data collector). When this happens, the system lists the registered data collectors' report as from an "unknown" number, and lists "0" in all report columns. It doesn’t appear to discriminate between who is sending the message - it just seems to be that every so often there is a hiccup. It has happened to several volunteers in the past. Not always from the same region and not always reporting on the same health risk.

**Expected behavior**
We would expect for the system to always recognise registered data collectors and correctly count the report in the report columns. 

- Could this issue be linked to issues #882 and #883?

**Screenshots**
![cbs platform issue](https://user-images.githubusercontent.com/40266417/50816828-12fe9200-1322-11e9-81e5-bb09f45bac74.png)

**Comment by mejdell** [comment]
This happened to us today when using the demo. Then it was because they number was not registered. Sender appears as unknown (which then of course makes sense), but the report is zero for gender and age although this was in the message. The same happened during the training in Dakar. It changed when number was registered. Not the same since you are now talking about numbers registered, but thought it was worth mentioning.

**Comment by RebeccaBushby** [comment]
Tine's comment above relates to issue #883 , but perhaps issues #885 , #882 and #883 are all linked?
